name: Deploy Quasar to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Quasar app
        run: npm run build
        env:
          NODE_ENV: production

      - name: Setup SPA for GitHub Pages
        run: |
          # Creează .nojekyll pentru a evita procesarea Jekyll
          touch ./dist/spa/.nojekyll
          
          # Creează 404.html pentru SPA routing (history mode)
          cp ./dist/spa/index.html ./dist/spa/404.html
          
          # Debug - arată ce fișiere avem
          echo "Files in dist/spa:"
          find ./dist/spa -type f | head -20
          echo "Total files: $(find ./dist/spa -type f | wc -l)"

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist/spa'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
